### ISSUE TITLE
Does the new update need to be set up from scratch?

### ISSUE THREAD

**Issue by msuspi** [talvo/potato#431]
Sorry if this is a dumb newbie question. I took quite some time to set up the last version of potato with my wolds, spawns, and the spellchecker. I downloaded the latest update and it has none of the old settings (which makes sense), but  is there a feature somewhere to pull all those old settings in?

Thank you so much!

Elizabeth

**Comment by talvo** [comment]
If you drop the new potato.exe (assuming you're on Windows) in the same place as the old one, it will use all your old settings, worlds, etc automatically.
