### ISSUE TITLE
Spellcheck as you type?

### ISSUE THREAD

**Issue by Kgencks** [talvo/potato#432]
I've just switched to Potato from SimpleMU* as I discovered I could not use my old key to register that program in Windows 10, and there seems unlikely that there will ever be a fix for that as it basically seems to be abandoned. The ONE SimpleMU* feature that was indispensable for me was the 'live' spellcheck that operated as you typed. 

Can Potato be modified to do that?

**Comment by talvo** [comment]
See #217; currently not possible, but hopefully at some point if I find a suitable library.
