### ISSUE TITLE
Exporting Address Book

### ISSUE THREAD

**Issue by PirateSpice** [talvo/potato#435]
I'm getting ready to completely overhaul my system and go from 32-bit to 64-bit. But I'd rather not have to completely reconstruct my Potato address book from scratch when I install it again. Is there any way to export the address book so I can just plug it in to the new Potato install?

**Comment by talvo** [comment]
It's all just stored in plain text files which you can back up and restore. If you're on Windows, you'll want potato.ini (for your program settings) and the worlds directory, located in the same place as your Potato .exe. If it's Linux or MacOS, you'll want to grab the ~/.potato/ directory.

**Comment by PirateSpice** [comment]
I did as you said, and I'm now using the 64-bit Windows version of Potato. But when I close Potato, I get a series of error popups telling me Potato couldn't save my preferences, worlds, etc. For instance, the first one reads:

'Unable to save preferences: couldn't open "C:/Program Files/Potato/potato/ini": permission denied'

I've got the Potato exe in the same folder as potato.ini and the worlds folder.

**Comment by PirateSpice** [comment]
I seem to have resolved the issue. Apparently Potato doesn't like being in the "Program Files" folder. I moved my Potato folder out of there and now it works fine.

**Comment by talvo** [comment]
Sorry for not getting back to you sooner. You are quite right; it can't write to certain system folders like Program Files. Right now Potato on Windows just runs as a single-file .exe and tries to write its settings, world info, etc, all the directory where the .exe is stored, so it needs to be put somewhere else (I recommend just C:\Potato for simplicity). At some point I intend to add in a proper installer, at which point it'll start writing all that info to the appropriate Application Data directory. (On Linux it already writes to ~/.potato/ by default.)
