### ISSUE TITLE
%T behavior not consistent with MU* code

### ISSUE THREAD

**Issue by Tyarra** [talvo/potato#436]
I haven't figured out exactly how Potato renders %T, but it doesn't recognize them as "tab stops" (if anyone remembers typing on an actual typewriter).   They should be recognized as being evenly spaced tab stops of 8 spaces each.

The following shows output from Potato, and from Another Client.  The second snip shows the MU* code used to generate the output.    If there is a setting within Potato to emulate this behavior, point me in that direction, otherwise, I'll add this to your list of bugs. 

![potato-tabbehavior](https://cloud.githubusercontent.com/assets/15351990/10775849/3638fb34-7cda-11e5-998e-ae54f1542dd9.png)

![cmud-tabbehavior](https://cloud.githubusercontent.com/assets/15351990/10775861/4404da94-7cda-11e5-9d29-ffcc6ef91af3.png)

**Comment by talvo** [comment]
They are being treated as tabs in Potato. Generally, though, using tabs is a bad idea for exactly this reason – the way they’re handled is not consistant between different outputs, so you can only hope/guess at how it might end up looking on someone’s display. (They don’t really have a clear meaning, even to how many characters wide they should be.) 

FWIW, you can get the behaviour you’re seeing in the second screenshot by creating a textfile called “potato.custom” (not “potato.custom.txt”) in the same directory as your Potato.exe with the line:

```
option add *Text.TabStyle wordprocessor
```

I’ll give some thought to changing the default behaviour to this. But, long story short, don’t rely on tabs giving a consistant output; I’ve seen clients that just translate `\t` into exactly 4 (and 8) spaces, as well as both behaviours you’ve shown below.

**Comment by Tyarra** [comment]
Worked perfectly!  Thank you!
