### ISSUE TITLE
Logging errors (no file extension)

### ISSUE THREAD

**Issue by Grendelgreg** [talvo/potato#437]
I have always used Potato to log my files to .txt files; the new version does not automatically append the filename with .txt unless the .txt is written directly in when saving the file.  I've been using 2.0.0b15 lately since it doesn't have this problem.  Any support on this would be great, I love Potato MUSH!

**Comment by talvo** [comment]
What OS are you using? And how are you logging, via the Log Window or the /log command?

**Comment by Grendelgreg** [comment]
I use Potato on Windows 7, Windows 8, and Windows 8.1.  The issue appears across all systems, and I log via the log window.

**Comment by talvo** [comment]
Looks like this was a deliberate change, but (at least on Windows) it should probably default to .txt
