### ISSUE TITLE
Kill open log streams with Disconnect

### ISSUE THREAD

**Issue by BlackRookSix** [talvo/potato#448]
Closing a world window properly closes the logging, but I am seeing instances where just disconnecting and leaving the window open leaves the log running.  So when I reconnect, I duplicate the log output because two /log streams are running?

Also, any idea what would cause line-duplication in logs?

Rook says, "Hey!"
Rook says, "Hey!"
Rook looks around.
Rook looks around.

**Comment by talvo** [comment]
This is deliberate; if you're using an Auto-Send to start logging, make sure you use the "Send upon first connect", not "Send upon connect", and you won't get duplicate logs then. (If you've got two logs open at the same time to the same file, that would account for the duplicated lines in there, too.)

**Comment by BlackRookSix** [comment]
Agreed, closing.  Thanks!
