### ISSUE TITLE
Telnet NOP Issue Persists In Mac Client

### ISSUE THREAD

**Issue by HeroicLeigh** [talvo/potato#451]
I see in the import from Google Code that this was noted as resolved. I've tried adjusting the settings within the Mac client, but I still get junk characters:

ÿñÿñÿñÿñÿñÿñÿñÿñÿñ<DB> Please wait, saving database.
<DB> Database save completed.
ÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñYou have exceeded the timeout and been CLOAKED.
ÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñÿñ<DB> Please wait, saving database.
<DB> Database save completed.

I have disabled the telnet options as in the closed ticket, but it does not fix the issue. I know people with the Windows client no longer have issues with Rhost, so it seems it may not be working on the Mac client.

**Comment by talvo** [comment]
How do you have them set? If memory serves, you'd need "Attempt Telnet Negotiation" on and "Abort Telnet after 90 seconds" off for a Rhost game.

**Comment by HeroicLeigh** [comment]
I was able to fix it. I don't even quite remember how, at this point. A lot of option fiddling. Meant to comment sooner, but life got crazy.
