### ISSUE TITLE
Prefixes/Auto Say menu issue

### ISSUE THREAD

**Issue by kalimalian** [talvo/potato#459]
Hi,

I was trying to set up a prefix for a spawn window, and I think I've broken something....

I'm running Potato 2.0.016b on Windows 8.1

When I click on the Configure Prefixes/Auto Say option, I get the following in a Potato Debugging Log window:

Dev file "C:\Users\<name>\Downloads\potato.dev" does not exist.
11 translations set for en_us.
308 translations set for es.
605 translations set for hr_hr.
607 translations set for no.
584 translations set for se.
Custom code file "C:\Users\<name>\Downloads\potato.custom" does not exist.
Startup Commands file "C:\Users\<name>\Downloads\potato.startup" does not exist.
Item heat not found
   Item heat not found
    while executing
"$tree selection set $first"
    (procedure "::potato::prefixWindow" line 55)
    invoked from within
"::potato::prefixWindow"
    (menu invoke)
Item heat not found
   Item heat not found
    while executing
"$tree selection set $first"
    (procedure "::potato::prefixWindow" line 55)
    invoked from within
"::potato::prefixWindow"
    (menu invoke)

(I've taken out my name from the file paths!)

There's a close button, which if I click I get the following window:

![image](https://cloud.githubusercontent.com/assets/22854951/19410162/d44be8cc-92dc-11e6-94b0-40b647ff0d95.png)

And I can't edit, add, or remove any prefixes.

Thanks :)

**Comment by talvo** [comment]
Fixed, thanks. Bug on my part caused it to not like the Window having a space in its name (if you change "heat stroke" to "heatstroke" or "heat_stroke" or something you can get around it until the next release).

**Comment by kalimalian** [comment]
Thanks Mike - I would remove the space but I can't edit any of the
prefixes. Should I just reinstall Potato and start afresh? When is the next
release likely to be?

**Comment by talvo** [comment]
*laughs* Right, good point. Close the Prefix Window, then go to Help -> Tcl Code Console, paste in http://pastebin.com/raw/S1Mtv4C2 and hit enter/return. Then you should be able to open the Prefix Window without the bug to make changes.

**Comment by kalimalian** [comment]
Thank you so much! I didn't expect such an amazingly quick response :P I can edit my prefixes again, whoopee!

**Comment by talvo** [comment]
My pleasure. :) Y'got lucky, I happened to be sitting here when you submitted it, and it was a really quick fix ;)
