### ISSUE TITLE
Would potato support for big5 encoding ?

### ISSUE THREAD

**Issue by kusan88** [talvo/potato#460]
I cannot find big5 encoding at Configuration Options > Connection > Starting Encoding.
Do you have any workaround for this ? 
Hope Potato will add big5 encoding support.
Thanks a lot.

**Comment by talvo** [comment]
I'll add support in for the next release.

**Comment by kusan88** [comment]
Thank you very much

**Comment by talvo** [comment]
I'm not sure why this didn't happen back in 2016, and I do apologise for not putting it in then as I said. big5 support has now been added in the git repo (at 53bd80ae7cc075faa6d57ac384c6abd7c3d273e6) and will be in the next release.
