### ISSUE TITLE
potato-2.0.0b17-win32-x86_64.exe missing package?

### ISSUE THREAD

**Issue by Ferretling** [talvo/potato#468]
I am trying to install 2.0.0b17 on my laptop running Windows 10. b 16 is currently working on the laptop. 2.0.0b17 downloads just fine. But when I try to run the program, I get the message "Required package base 64 is missing" Please re-download or contact the author.

**Comment by heysparky** [comment]
I'm getting this too. 

base64 error: [http://tinypic.com/r/287lkir/9](url)

**Comment by talvo** [comment]
Hrm! I'm not sure why this is (it's working for me and at least some others), but I will try and figure it out ASAP.

**Comment by talvo** [comment]
Ah! Found the problem - there's an issue with it being run from a directory with a space in the name in one of the libraries being used. I'll try and get a fixed build out over the weekend, but in the meantime, moving to a directory with no space in the name (C:\Potato, or something similar) should work around it.

**Comment by NathanAdored** [comment]
It was stated there would be a fix out in a couple of days.  It's been more than a week, and the newest 64bit windows version of Potato is still giving that same "Required package base 64 is missing" error when placed into a path with spaces in it.

**Comment by smreyno** [comment]
I'm still getting this error as well when I try to download the new version.

**Comment by Xeones** [comment]
Also having this issue, though it seems the root of the problem has been identified, and will probably be fixed in the next version. But, for the sake of completeness, I'll note that the same thing happens with the 32 bit version, all the way back on Windows XP (though the same temporary fix also works).

**Comment by talvo** [comment]
Sorry for the massive delay, folks, I got swamped by RL. Bugfix is in, now, and I'll be trying to put out a new release on Saturday, if I can.
