### ISSUE TITLE
Can't install 2.0.0b17

### ISSUE THREAD

**Issue by Jtwgeek** [talvo/potato#476]
The error I get when I try to run the download is... 

Required package base64 is missing.
Please re-download Potato from the website
(http://www.potatomushclient.com/) and contact the author if you have any further problems. 

After I hit okay it pops up with another error window.

Error: wrong # args: should be 'source?-encoding name? fileName"

I have tried downloading both the 64 bit version and the 32 and they both give me the same error.

**Comment by talvo** [comment]
See #468; there's a bug that means that version of Potato won't run from a directory with spaces in its name. The bug is fixed, but I (still) haven't released a new version yet. You can work around temporarily by renaming/moving the dir Potato is in so there are no spaces.
