### ISSUE TITLE
Change Input Font control not showing

### ISSUE THREAD

**Issue by ockapus** [talvo/potato#486]
Recently installed on a new laptop running Windows 10, and am having trouble updating the display settings. I can change the output font just fine, both on a program and world level. But while there is a column of labels visible for Change Input Font, Allow ANSI Underline? and Force ANSI Normal, there are no actual controls accessible to update those values. This remains true even when I resize the window or attempt scrolling what's visible in that window.

**Comment by talvo** [comment]
Can you attach a screenshot of the window? It should look like this:

![config-fonts-colours](https://user-images.githubusercontent.com/10090715/34587717-6cf169c0-f1a1-11e7-9108-52c47d0b347e.png)

With buttons for the fonts and checkbuttons for the ANSI options.

**Comment by ockapus** [comment]
Oh heck, sorry for the false alarm. I saw this happen on a new laptop, where I was /certain/ I had rebooted after turning off the screen resolution scaling from 150% down to 100%. However, looks like I hadn't actually managed, because the next day after I had done a full reboot those options were accessible as expected again.

**Comment by talvo** [comment]
Ahh; no worries. Yeah, it's a known issue that stuff doesn't work well with resolution scaling, but I've not gotten around to working on that yet.
