### ISSUE TITLE
Bit-Defender randomly decided Potato was Malware

### ISSUE THREAD

**Issue by DFX2KX** [talvo/potato#489]
I have no idea why, but I noticed it after BD killed the process and deleted all of my wld files. I went and pulled up Windows 7's Previous version mode to restore them and it did so again.

After finally realizing it was the Anti-Virus doing it, I went into quarentine to see what detection it had Triggered, it said ad4.detection. Did this with both the 32 and 64 bit versions downloaded straight off the site. Figured I aught to let you guys know

**Comment by DFX2KX** [comment]
(and naturally I can't post the screen capture of the window I snagged with the snippter tool, go figure, thanks, Github)

**Comment by talvo** [comment]
Thanks for the heads-up - would you mind emailing the screenshot (mike@keyboardzombie.com)? I'll see if I can get it whitelisted.

**Comment by DFX2KX** [comment]
Done!

BitDefender is hyper-picky about what it'll let run, So I'm fairly sure it's heuristics decided that Potato did something bad for some reason (the other flags I've gotten where from a pixel-art editor of all things)

**Comment by talvo** [comment]
That's great, thanks; I've submitted it as a false-positive to BitDefender, so hopefully they'll whitelist it. (The way that the Windows binaries are built does occassionally cause some AVs to panic, unfortunately.)

**Comment by talvo** [comment]
Closing this as it's now down to BitDefender, but hopefully they've whitelisted me :)
