### ISSUE TITLE
Potato isn't displaying unicode characters correctly

### ISSUE THREAD

**Issue by taladan** [talvo/potato#492]
OS: Linux Mint 18

Using: Deja Vu sans mono 12pt font

Supposed to output unicode box characters, but they're not displaying correctly.

Attaching screenshot.
![screen](https://user-images.githubusercontent.com/2736361/37004168-8ec0bb20-209d-11e8-8f86-077e53abdede.png)

**Comment by talvo** [comment]
Solved; world wasn't negotiating charset, so it had to be set to utf-8 in the settings before connecting.
